begin;

create extension if not exists pgtap with schema extensions;
set search_path = extensions, public;

select plan(41);

select has_column('public','sales','cash_amount','sales cash amount exists');
select has_column('public','sales','upi_amount','sales UPI amount exists');
select has_column('public','day_end_summaries','expected_total','day-end expected total exists');
select has_column('public','shop_settings','allow_below_cost_sales','below-cost policy exists');
select has_column('public','shop_settings','dashboard_reset_time','dashboard reset time exists');
select has_column('public','shop_settings','allow_zero_price_sales','zero-price policy exists');
select has_table('public','automatic_day_end_snapshots','automatic snapshots table exists');

select ok(
  (select attgenerated = 's' from pg_attribute where attrelid='public.daily_closings'::regclass and attname='difference'),
  'daily closing difference is generated by PostgreSQL'
);

select ok(
  not has_table_privilege('authenticated','public.inventory_purchases','INSERT'),
  'authenticated cannot directly insert purchase rows'
);

select ok(
  has_table_privilege('authenticated','public.products','UPDATE'),
  'authenticated has update grant but product RLS limits direct updates'
);

select is_definer('public.record_sale(uuid,uuid,numeric,numeric,text,numeric,text,numeric,numeric)','record_sale is security definer');
select is_definer('public.submit_daily_closing(date,numeric,numeric,uuid)','daily closing RPC is security definer');
select is_definer('public.submit_day_end_summary(uuid)','day-end submit RPC is security definer');
select is_definer('public.confirm_day_end_summary(uuid)','day-end confirm RPC is security definer');

-- Create two local auth users; the schema trigger creates their shop profiles.
insert into auth.users(id,email)
values
  ('11111111-1111-1111-1111-111111111111','shop-owner-test@example.com'),
  ('22222222-2222-2222-2222-222222222222','shop-worker-test@example.com');

update public.profiles
set role='owner',is_active=true,full_name='Test Owner'
where id='11111111-1111-1111-1111-111111111111';

update public.profiles
set role='worker',is_active=true,full_name='Test Worker'
where id='22222222-2222-2222-2222-222222222222';

set local role authenticated;
set local request.jwt.claim.sub = '11111111-1111-1111-1111-111111111111';

select lives_ok(
  $$select public.create_product('pgTAP Test Product','piece'::public.product_unit,0,5,8,1)$$,
  'owner can create a product'
);

select lives_ok(
  $$select public.add_inventory_purchase(
    (select id from public.products where name='pgTAP Test Product'),
    10,10,'piece',5
  )$$,
  'owner purchase RPC adds stock'
);

select results_eq(
  $$select current_stock_base from public.products where name='pgTAP Test Product'$$,
  $$values(10::numeric)$$,
  'purchase increases stock'
);

select lives_ok(
  $$select public.record_sale(
    (select id from public.products where name='pgTAP Test Product'),
    '11111111-1111-1111-1111-111111111111',
    2,2,'piece',8,'cash',16,0
  )$$,
  'owner can record a sale'
);

select results_eq(
  $$select current_stock_base from public.products where name='pgTAP Test Product'$$,
  $$values(8::numeric)$$,
  'sale decreases stock atomically'
);

select results_eq(
  $$select total_sale,gross_profit,cash_amount,upi_amount from public.sales where product_id=(select id from public.products where name='pgTAP Test Product')$$,
  $$values(16::numeric,6::numeric,16::numeric,0::numeric)$$,
  'sale totals and profit are recorded correctly'
);

select results_eq(
  $select total_sales,total_profit,transactions,cash_amount,upi_amount from public.automatic_day_end_snapshots$,
  $values(16::numeric,6::numeric,1::integer,16::numeric,0::numeric)$,
  'automatic day-end snapshot is persisted from the sale'
);

select ok(
  not has_table_privilege('authenticated','public.products','DELETE'),
  'authenticated cannot directly delete products'
);

select lives_ok(
  $select public.create_product('Permanent Delete Test','piece'::public.product_unit,2,5,8,1)$,
  'owner can create a product for permanent-delete testing'
);

select public.record_sale(
  (select id from public.products where name='Permanent Delete Test'),
  '11111111-1111-1111-1111-111111111111',
  1,1,'piece',8,'cash',8,0
);

select lives_ok(
  $select public.delete_product((select id from public.products where name='Permanent Delete Test'))$,
  'owner can permanently delete a product'
);

select results_eq(
  $select count(*) from public.products where name='Permanent Delete Test'$,
  $values(0::bigint)$,
  'deleted product row is removed from products'
);

select results_eq(
  $select product_id,product_name_snapshot from public.sales where product_name_snapshot='Permanent Delete Test'$,
  $values(null::uuid,'Permanent Delete Test')$,
  'historical sale keeps its product name after deletion'
);

select lives_ok(
  $select public.create_product('Permanent Delete Test','piece'::public.product_unit,0,6,9,1)$,
  'same product name can be created again after deletion'
);

set local request.jwt.claim.sub = '22222222-2222-2222-2222-222222222222';

select results_eq(
  $$select count(*) from public.sales$$,
  $$values(0::bigint)$$,
  'worker cannot see another worker/owner sales through RLS'
);

select throws_ok(
  $update public.products set current_stock_base=999 where name='pgTAP Test Product'$,
  '42501',
  null,
  'worker cannot directly modify product stock'
);

set local request.jwt.claim.sub = '11111111-1111-1111-1111-111111111111';

select lives_ok(
  $$select public.clear_all_shop_data()$$,
  'owner can clear transaction data'
);

select results_eq(
  $$select count(*) from public.audit_logs where action='shop_data_cleared'$$,
  $$values(1::bigint)$$,
  'clear-all leaves an audit record'
);

select results_eq(
  $$select count(*) from public.inventory_purchases$$,
  $$values(0::bigint)$$,
  'clear-all preserves its existing transaction-clearing behavior'
);



select throws_ok(
  $q$insert into public.sales(product_id,worker_id,quantity_base,quantity_display,sold_unit,total_sale,total_cost,gross_profit,selling_price_per_base_unit,purchase_price_per_base_unit)
      values((select id from public.products where name='pgTAP Test Product'),'22222222-2222-2222-2222-222222222222',1,1,'piece',8,5,3,8,5)$q$,
  '42501', null, 'worker cannot insert a sale directly'
);

select set_config('request.jwt.claim.sub','22222222-2222-2222-2222-222222222222',true);
select throws_ok(
  $q$select public.record_sale((select id from public.products where name='pgTAP Test Product'),'11111111-1111-1111-1111-111111111111',1,1,'piece',8,'cash',8,0)$q$,
  'Worker can only record sales for self', null, 'worker cannot record another user sale'
);
select throws_ok(
  $q$select public.record_sale((select id from public.products where name='pgTAP Test Product'),'22222222-2222-2222-2222-222222222222',1,1,'piece',8,'split',5,1)$q$,
  'Cash + UPI must equal the sale total', null, 'split payments must reconcile'
);

set local request.jwt.claim.sub = '11111111-1111-1111-1111-111111111111';
select public.record_sale((select id from public.products where name='pgTAP Test Product'),'11111111-1111-1111-1111-111111111111',1,1,'piece',8,'cash',8,0);
select public.submit_daily_closing(current_date,24,0,null);
select public.approve_closing((select id from public.daily_closings where worker_id='11111111-1111-1111-1111-111111111111' and business_date=current_date));
select public.lock_closing((select id from public.daily_closings where worker_id='11111111-1111-1111-1111-111111111111' and business_date=current_date));
select results_eq(
  $$select status::text from public.daily_closings where worker_id='11111111-1111-1111-1111-111111111111' and business_date=current_date$$,
  $$values('locked'::text)$$,
  'owner can approve and lock a closing'
);
select throws_ok(
  $q$update public.daily_closings set cash_amount=0 where worker_id='11111111-1111-1111-1111-111111111111' and business_date=current_date$q$,
  '42501', null, 'direct closing updates are blocked'
);
select public.void_sale((select id from public.sales where worker_id='11111111-1111-1111-1111-111111111111' and not voided limit 1));
select results_eq(
  $$select current_stock_base from public.products where name='pgTAP Test Product'$$,
  $$values(7::numeric)$$,
  'void restores stock'
);

update public.shop_settings set allow_below_cost_sales=false,allow_zero_price_sales=false where id=1;
select set_config('request.jwt.claim.sub','22222222-2222-2222-2222-222222222222',true);
select throws_ok(
  $q$select public.record_sale((select id from public.products where name='pgTAP Test Product'),'22222222-2222-2222-2222-222222222222',1,1,'piece',4,'cash',4,0)$q$,
  'Below-cost sales are disabled in shop settings', null, 'below-cost sales can be disabled'
);
select throws_ok(
  $q$select public.record_sale((select id from public.products where name='pgTAP Test Product'),'22222222-2222-2222-2222-222222222222',1,1,'piece',0,'cash',0,0)$q$,
  'Zero-price sales are disabled in shop settings', null, 'zero-price sales can be disabled'
);
update public.profiles set is_active=false where id='22222222-2222-2222-2222-222222222222';
select throws_ok(
  $q$select public.record_sale((select id from public.products where name='pgTAP Test Product'),'22222222-2222-2222-2222-222222222222',1,1,'piece',8,'cash',8,0)$q$,
  'Account is inactive', null, 'inactive worker cannot sell'
);

select * from finish();
rollback;
