project_id = "shop-management"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
major_version = 17

[studio]
enabled = false

[inbucket]
enabled = false
