import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import "./styles.css";

type Role="owner"|"worker";
type Profile={id:string;full_name:string;email:string;role:Role;is_active:boolean;shop_id?:string};
type Product={id:string;name:string;unit_type:"piece"|"weight";current_stock_base:number;purchase_price_per_base_unit:number;selling_price_per_base_unit:number;low_stock_threshold_base:number;is_active:boolean};
type Sale=any; type Purchase=any; type Creditor=any; type Ledger=any; type Daily=any;
const URL_KEY="shop_management_supabase_url", KEY_KEY="shop_management_supabase_publishable_key";
let supabase:SupabaseClient|null=null, profile:Profile|null=null, settings:any={shop_name:"My Shop",currency:"INR",timezone:"Asia/Kolkata",workers_can_modify_selling_price:false};
let products:Product[]=[], sales:Sale[]=[], purchases:Purchase[]=[], creditorList:Creditor[]=[], ledger:Ledger[]=[], daily:Daily[]=[], lifetime:any=null;
let demo=false, activeTab="dashboard", historyType="sales", historyRange="7", reportDate="";
let cartItems:any[]=[];
const app=document.querySelector<HTMLDivElement>("#app")!;

const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:settings.currency||"INR",maximumFractionDigits:2}).format(Number(n)||0);
const esc=(s:any)=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const localDate=(d=new Date())=>new Intl.DateTimeFormat("en-CA",{timeZone:settings.timezone||"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);
const fmt=(d:any)=>d?new Date(d).toLocaleString("en-IN",{dateStyle:"short",timeStyle:"short"}):"";
const notify=(m:string,t="info")=>{const x=document.createElement("div");x.className="toast "+t;x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)};
const readConn=()=>({url:localStorage.getItem(URL_KEY)||"",key:localStorage.getItem(KEY_KEY)||""});
const connect=()=>{const c=readConn();if(c.url&&c.key){supabase=createClient(c.url,c.key);return true}return false};

function demoClient(){
 const owner={id:"demo-owner",full_name:"Demo Owner",email:"owner@demo.shop",role:"owner",is_active:true,shop_id:"SHOP-DEMO0001"};
 const worker={id:"demo-worker",full_name:"Demo Worker",email:"worker@demo.shop",role:"worker",is_active:true,shop_id:"SHOP-DEMO0001"};
 const ps:Product[]=[
  {id:"p1",name:"Tata Salt 1kg",unit_type:"piece",current_stock_base:48,purchase_price_per_base_unit:24,selling_price_per_base_unit:30,low_stock_threshold_base:10,is_active:true},
  {id:"p2",name:"Aashirvaad Atta 5kg",unit_type:"piece",current_stock_base:18,purchase_price_per_base_unit:210,selling_price_per_base_unit:255,low_stock_threshold_base:5,is_active:true},
  {id:"p3",name:"Fortune Oil 1L",unit_type:"piece",current_stock_base:27,purchase_price_per_base_unit:112,selling_price_per_base_unit:135,low_stock_threshold_base:8,is_active:true},
  {id:"p4",name:"Toor Dal 1kg",unit_type:"piece",current_stock_base:9,purchase_price_per_base_unit:118,selling_price_per_base_unit:145,low_stock_threshold_base:10,is_active:true},
  {id:"p5",name:"Basmati Rice 5kg",unit_type:"piece",current_stock_base:6,purchase_price_per_base_unit:410,selling_price_per_base_unit:475,low_stock_threshold_base:8,is_active:true}
 ];
 const ago=(n:number,h=12)=>{const d=new Date();d.setDate(d.getDate()-n);d.setHours(h,15,0,0);return d.toISOString()};
 const ss:any[]=[
  {id:"s1",sold_at:ago(0,10),product_id:"p1",worker_id:worker.id,total_sale:120,gross_profit:24,cash_amount:120,upi_amount:0,payment_mode:"cash",quantity_base:4,quantity_display:4,sold_unit:"piece",voided:false,products:{name:"Tata Salt 1kg"},profiles:{full_name:"Demo Worker"}},
  {id:"s2",sold_at:ago(0,13),product_id:"p2",worker_id:worker.id,total_sale:510,gross_profit:90,cash_amount:200,upi_amount:310,payment_mode:"split",quantity_base:2,quantity_display:2,sold_unit:"piece",voided:false,products:{name:"Aashirvaad Atta 5kg"},profiles:{full_name:"Demo Worker"}},
  {id:"s3",sold_at:ago(1,16),product_id:"p3",worker_id:owner.id,total_sale:270,gross_profit:46,cash_amount:0,upi_amount:270,payment_mode:"upi",quantity_base:2,quantity_display:2,sold_unit:"piece",voided:false,products:{name:"Fortune Oil 1L"},profiles:{full_name:"Demo Owner"}},
  {id:"s4",sold_at:ago(2,11),product_id:"p4",worker_id:worker.id,total_sale:290,gross_profit:54,cash_amount:290,upi_amount:0,payment_mode:"cash",quantity_base:2,quantity_display:2,sold_unit:"piece",voided:false,products:{name:"Toor Dal 1kg"},profiles:{full_name:"Demo Worker"}},
  {id:"s5",sold_at:ago(5,14),product_id:"p5",worker_id:owner.id,total_sale:950,gross_profit:130,cash_amount:500,upi_amount:450,payment_mode:"split",quantity_base:2,quantity_display:2,sold_unit:"piece",voided:false,products:{name:"Basmati Rice 5kg"},profiles:{full_name:"Demo Owner"}}
 ];
 const cr=[{id:"c1",name:"Rahul Sharma",mobile:"9876543210"},{id:"c2",name:"Priya Traders",mobile:"9123456780"}];
 const lg=[{id:"l1",creditor_id:"c1",type:"credit_sale",amount:850,payment_mode:"credit",created_at:ago(3),worker_id:worker.id,profiles:{full_name:"Demo Worker"}},{id:"l2",creditor_id:"c1",type:"payment_received",amount:300,payment_mode:"cash",cash_amount:300,upi_amount:0,created_at:ago(1),worker_id:owner.id,profiles:{full_name:"Demo Owner"}},{id:"l3",creditor_id:"c2",type:"credit_sale",amount:420,payment_mode:"credit",created_at:ago(7),worker_id:worker.id,profiles:{full_name:"Demo Worker"}}];
 const pur=[{id:"q1",product_id:"p1",product_name_snapshot:"Tata Salt 1kg",quantity_base:20,quantity_display:20,purchase_unit:"piece",purchase_price_per_base_unit:23,total_cost:460,purchased_at:ago(2),purchased_by:owner.id,profiles:{full_name:"Demo Owner"}}];
 const ds:any[]=[];for(let i=0;i<12;i++)ds.push({shop_id:"SHOP-DEMO0001",business_date:localDate(new Date(Date.now()-i*86400000)),total_transactions:i?1:2,total_revenue:i?270:630,cash_sales:i?0:320,upi_sales:i?270:310,credit_sales:i?0:0,total_profit:i?46:114,cash_profit:i?0:24,upi_profit:i?46:90,credit_profit:0,creditor_amount:0,total_purchases:i?0:460});
 return {owner,worker,products:ps,sales:ss,creditorList:cr,ledger:lg,purchases:pur,daily:ds,lifetime:{lifetime_sales:2140,lifetime_purchases:1780,lifetime_profit:344}};
}

function qBalance(id:string){return ledger.filter(x=>x.creditor_id===id).reduce((a,x)=>a+(x.type==="credit_sale"||x.type==="adjustment"?Number(x.amount):-Number(x.amount)),0)}
function currentSales(){const today=localDate();return sales.filter(s=>!s.voided&&localDate(new Date(s.sold_at))===today)}
function currentStats(){const a=currentSales();return {tx:new Set(a.map(x=>x.transaction_id||x.id)).size,sales:a.reduce((x,y)=>x+Number(y.total_sale||0),0),profit:a.reduce((x,y)=>x+Number(y.gross_profit||0),0),cash:a.reduce((x,y)=>x+Number(y.cash_amount||0),0),upi:a.reduce((x,y)=>x+Number(y.upi_amount||0),0)}}

async function loadData(){
 if(demo){const d=demoClient();products=d.products;sales=d.sales;purchases=d.purchases;creditorList=d.creditorList;ledger=d.ledger;daily=d.daily;lifetime=d.lifetime;settings={shop_name:"Demo Grocery Store",currency:"INR",timezone:"Asia/Kolkata",workers_can_modify_selling_price:true};return}
 if(!supabase||!profile)return;
 const [set,p,s,q,c,l,df,life]=await Promise.all([
  supabase.from("shop_settings").select("*").limit(1).maybeSingle(),
  supabase.from("products").select("*").eq("is_active",true).order("name"),
  supabase.from("sales").select("*,products(name),profiles:worker_id(full_name)").order("sold_at",{ascending:false}).limit(1000),
  supabase.from("inventory_purchases").select("*,profiles:purchased_by(full_name)").order("purchased_at",{ascending:false}).limit(1000),
  supabase.from("creditorList").select("*").order("name"),
  supabase.from("credit_ledger").select("*,profiles:worker_id(full_name)").order("created_at",{ascending:false}).limit(2000),
  supabase.from("daily_financial_summaries").select("*").order("business_date",{ascending:false}).limit(400),
  supabase.from("lifetime_financial_summaries").select("*").limit(1).maybeSingle()
 ]);
 if(set.data)settings=set.data;
 products=p.data||[];sales=s.data||[];purchases=q.data||[];creditorList=c.data||[];ledger=l.data||[];daily=df.data||[];lifetime=life.data;
}

async function saveSale(item:any,mode:string,cash:number,upi:number,credit:number,creditor:string|null){
 if(demo){const p=products.find(x=>x.id===item.product_id);if(!p)return;const total=Number(item.quantity_base)*Number(item.selling_price_per_base_unit);sales.unshift({id:"demo-"+Date.now(),sold_at:new Date().toISOString(),product_id:p.id,product_name_snapshot:p.name,worker_id:profile!.id,quantity_base:item.quantity_base,quantity_display:item.quantity_display,sold_unit:item.sold_unit,payment_mode:mode,cash_amount:cash,upi_amount:upi,total_sale:total,gross_profit:(Number(item.selling_price_per_base_unit)-p.purchase_price_per_base_unit)*Number(item.quantity_base),voided:false,products:{name:p.name},profiles:{full_name:profile!.full_name}});p.current_stock_base-=Number(item.quantity_base);if(credit>0&&creditor)ledger.unshift({id:"demo-"+Date.now(),creditor_id:creditor,type:"credit_sale",amount:credit,payment_mode:mode,created_at:new Date().toISOString(),worker_id:profile!.id,profiles:{full_name:profile!.full_name}});return}
 if(!supabase)throw new Error("Supabase is not connected.");
 const {error}=await supabase.rpc("complete_cart_sale",{p_worker_id:profile!.id,p_items:[item],p_payment_mode:mode,p_cash_amount:cash,p_upi_amount:upi,p_credit_amount:credit,p_creditor_id:creditor});
 if(error)throw error;
}

function shell(title:string,body:string){
 const owner=profile?.role==="owner";
 const nav=[["dashboard","Dashboard"],["sale","Add Sale"],["cart","Cart"],["stock","Stock"],["creditorList","Creditors"],["history","History"],...(owner?[["today","Today Stats"],["reports","Reports"],["workers","Workers"],["audit","Audit"],["settings","Settings"]]:[])];
 return `<div class="app-shell"><header><div><b>${esc(settings.shop_name)}</b><span class="muted">${esc(title)}</span></div><button id="logout" class="ghost small">Sign out</button></header><main><div id="view"></div></main><nav class="bottom-nav">${nav.map(([id,n])=>`<button data-nav="${id}" class="${activeTab===id?"active":""}">${esc(n)}</button>`).join("")}</nav></div>`;
}

function dashboard(){
 const low=products.filter(p=>Number(p.current_stock_base)<=Number(p.low_stock_threshold_base));
 return `<section class="page"><div class="page-head"><div><h2>Dashboard</h2><p class="muted">Stock and quick actions.</p></div><button id="refresh" class="ghost">Refresh</button></div>
 <div class="quick-grid"><button data-nav="sale">＋ Add Sale</button><button data-nav="cart">🛒 Cart</button><button data-nav="stock">Stock</button><button data-nav="creditorList">Creditors</button></div>
 <div class="panel"><div class="section-head"><h3>Stock</h3><span class="badge">${products.length} products</span></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Stock</th><th>Sell</th><th>Status</th></tr></thead><tbody>${products.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.current_stock_base} ${p.unit_type==="piece"?"pcs":"base"}</td><td>${money(p.selling_price_per_base_unit)}</td><td>${Number(p.current_stock_base)<=Number(p.low_stock_threshold_base)?'<span class="badge warn">LOW</span>':'<span class="badge ok">OK</span>'}</td></tr>`).join("")}</tbody></table></div>${low.length?`<div class="notice warning">${low.length} product(s) are low in stock.</div>`:""}</div></section>`;
}

function sale(){
 return `<section class="page"><h2>Add Sale</h2><div class="panel"><label>Search product<input id="saleSearch" placeholder="Search product..."></label><div id="saleProducts" class="product-grid">${products.map((p,i)=>`<button class="product-card ${i>1?"extra-product":""}" data-product="${p.id}"><b>${esc(p.name)}</b><span>${p.current_stock_base} available</span><strong>${money(p.selling_price_per_base_unit)}</strong></button>`).join("")}</div>
 <form id="saleForm" class="form-grid"><label>Product<select name="product" required>${products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}</select></label><label>Quantity<input name="qty" type="number" min="0.001" step="0.001" value="1" required></label><label>Unit<select name="unit"><option value="piece">pieces</option><option value="grams">grams</option><option value="kg">kg</option></select></label><label>Selling price<input name="price" type="number" step=".01" min="0" required></label><label>Payment<select name="mode"><option value="cash">Cash</option><option value="upi">UPI</option><option value="split">Cash + UPI</option><option value="credit">Credit</option><option value="credit_split">Credit + Cash + UPI</option></select></label><label id="cashBox" class="hidden">Cash<input name="cash" type="number" step=".01" min="0" value="0"></label><label id="upiBox" class="hidden">UPI<input name="upi" type="number" step=".01" min="0" value="0"></label><label id="creditBox" class="hidden">Credit<input name="credit" type="number" step=".01" min="0" value="0"></label><label id="creditorBox" class="hidden">Creditor<select name="creditor"><option value="">Select creditor</option>${creditorList.map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.mobile)}</option>`).join("")}</select></label><div class="full"><div id="saleTotal" class="notice">Total: ₹0.00</div></div><button class="primary full">Complete Sale</button></form></div></section>`;
}

function cart(){
 const total=cartItems.reduce((a,x)=>a+Number(x.quantity_base)*Number(x.selling_price_per_base_unit),0);
 return `<section class="page"><div class="page-head"><h2>Cart</h2><span class="badge">${cartItems.length} item(s)</span></div>
 <div class="panel"><form id="cartAdd" class="form-grid"><label>Product<select name="product">${products.map(p=>`<option value="${p.id}">${esc(p.name)} — ${p.current_stock_base} available</option>`).join("")}</select></label><label>Quantity<input name="qty" type="number" min="0.001" step=".001" value="1"></label><label>Unit<select name="unit"><option value="piece">pieces</option><option value="grams">grams</option><option value="kg">kg</option></select></label><label>Selling price<input name="price" type="number" min="0" step=".01"></label><button class="primary full">Add to Cart</button></form></div>
 <div class="panel"><div class="table-wrap"><table><thead><tr><th>Product</th><th>Qty</th><th>Price</th><th>Total</th><th></th></tr></thead><tbody>${cartItems.map((x,i)=>{const p=products.find(p=>p.id===x.product_id);return `<tr><td>${esc(p?.name||"")}</td><td>${x.quantity_display}</td><td>${money(x.selling_price_per_base_unit)}</td><td>${money(x.quantity_base*x.selling_price_per_base_unit)}</td><td><button class="smallbtn edit-cart" data-i="${i}">Edit</button> <button class="smallbtn del-cart" data-i="${i}">Delete</button></td></tr>`}).join("")||'<tr><td colspan="5" class="muted">Cart is empty.</td></tr>'}</tbody></table></div><div class="notice"><b>Total: ${money(total)}</b></div></div>
 <div class="panel"><form id="cartPay" class="form-grid"><label>Payment<select name="mode"><option value="cash">Cash</option><option value="upi">UPI</option><option value="split">Cash + UPI</option><option value="credit">Credit</option><option value="credit_split">Credit + Cash + UPI</option></select></label><label id="cartCashBox" class="hidden">Cash<input name="cash" type="number" min="0" step=".01" value="0"></label><label id="cartUpiBox" class="hidden">UPI<input name="upi" type="number" min="0" step=".01" value="0"></label><label id="cartCreditBox" class="hidden">Credit<input name="credit" type="number" min="0" step=".01" value="0"></label><label id="cartCreditorBox" class="hidden">Creditor<select name="creditor"><option value="">Select creditor</option>${creditorList.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("")}</select></label><button class="primary full" type="submit">Confirm Cart Sale</button></form></div></section>`;
}
function stock(){
 return `<section class="page"><div class="page-head"><h2>Stock</h2><button id="addPurchase" class="primary">＋ Purchase</button></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Product</th><th>Current</th><th>Buy</th><th>Sell</th></tr></thead><tbody>${products.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.current_stock_base}</td><td>${money(p.purchase_price_per_base_unit)}</td><td>${money(p.selling_price_per_base_unit)}</td></tr>`).join("")}</tbody></table></div></div><div id="purchaseForm"></div></section>`;
}
function creditors(){
 return `<section class="page"><div class="page-head"><h2>Creditors</h2><button id="newCreditor" class="primary">＋ Add</button></div><div class="panel"><label>Search<input id="creditSearch" placeholder="Name or mobile..."></label><div class="table-wrap"><table><thead><tr><th>Name</th><th>Mobile</th><th>Outstanding</th><th></th></tr></thead><tbody>${creditorList.map(c=>`<tr class="credit-row" data-q="${esc((c.name+" "+c.mobile).toLowerCase())}"><td>${esc(c.name)}</td><td>${esc(c.mobile)}</td><td class="${qBalance(c.id)>0?"negative":"positive"}">${money(qBalance(c.id))}</td><td><button class="smallbtn pay-credit" data-id="${c.id}">Pay</button> <button class="smallbtn credit-history" data-id="${c.id}">History</button></td></tr>`).join("")}</tbody></table></div></div><div id="creditDetail"></div></section>`;
}
function history(){
 return `<section class="page"><div class="page-head"><h2>History</h2><span class="muted">Details are retained only for the configured period.</span></div><div class="seg"><button class="${historyType==="sales"?"active":""}" data-history="sales">Sales</button><button class="${historyType==="purchases"?"active":""}" data-history="purchases">Purchases</button></div><div class="seg"><button class="${historyRange==="7"?"active":""}" data-range="7">Last 7 Days</button><button class="${historyRange==="30"?"active":""}" data-range="30">Last 1 Month</button><button class="${historyRange==="date"?"active":""}" data-range="date">Search Date</button></div>${historyRange==="date"?'<input id="historyDate" type="date" value="'+esc(reportDate||localDate())+'">':""}<div class="panel"><div class="table-wrap">${historyTable()}</div></div></section>`;
}
function historyTable(){
 const start=historyRange==="7"?Date.now()-7*864e5:historyRange==="30"?Date.now()-30*864e5:0;
 const rows=historyType==="sales"?sales.filter(s=>!s.voided&&(!start||new Date(s.sold_at).getTime()>=start)&&(!reportDate||historyRange!=="date"||localDate(new Date(s.sold_at))===reportDate)):purchases.filter(p=>(!start||new Date(p.purchased_at).getTime()>=start)&&(!reportDate||historyRange!=="date"||localDate(new Date(p.purchased_at))===reportDate));
 if(historyType==="sales")return `<table><thead><tr><th>Date</th><th>Product</th><th>Qty</th><th>Sale</th><th>Profit</th><th>Payment</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${fmt(s.sold_at)}</td><td>${esc(s.products?.name||s.product_name_snapshot)}</td><td>${s.quantity_display}</td><td>${money(s.total_sale)}</td><td>${money(s.gross_profit)}</td><td>${esc(s.payment_mode)}</td></tr>`).join("")||'<tr><td colspan="6" class="muted">No retained sale details.</td></tr>'}</tbody></table>`;
 return `<table><thead><tr><th>Date</th><th>Product</th><th>Qty</th><th>Cost</th><th>By</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${fmt(p.purchased_at)}</td><td>${esc(p.product_name_snapshot)}</td><td>${p.quantity_display}</td><td>${money(p.total_cost)}</td><td>${esc(p.profiles?.full_name||"")}</td></tr>`).join("")||'<tr><td colspan="5" class="muted">No retained purchase details.</td></tr>'}</tbody></table>`;
}
function today(){
 const s=currentStats(),low=products.filter(p=>Number(p.current_stock_base)<=Number(p.low_stock_threshold_base));
 return `<section class="page"><h2>Today Stats</h2><p class="muted">${localDate()}</p><div class="metrics">${m("Sales",money(s.sales))}${m("Profit",money(s.profit))}${m("Cash",money(s.cash))}${m("UPI",money(s.upi))}${m("Transactions",String(s.tx))}${m("Products",String(products.length))}${m("Low Stock",String(low.length))}</div><div class="panel"><h3>Reconciliation</h3><p>Sales cash + UPI: <b>${money(s.cash+s.upi)}</b></p><p>Recorded sales: <b>${money(s.sales)}</b></p><p class="${Math.abs(s.cash+s.upi-s.sales)<.01?"positive":"negative"}">${Math.abs(s.cash+s.upi-s.sales)<.01?"Balanced":"Difference: "+money(s.cash+s.upi-s.sales)}</p></div></section>`;
}
const m=(l:string,v:string)=>`<div class="metric"><span>${l}</span><b>${v}</b></div>`;

function reports(){
 const recent=daily.slice(0,7), total=lifetime||{lifetime_sales:0,lifetime_purchases:0,lifetime_profit:0};
 const selected=reportDate?daily.find(x=>x.business_date===reportDate):null;
 return `<section class="page"><h2>Reports</h2><div class="metrics">${m("Lifetime Sales",money(total.lifetime_sales))}${m("Lifetime Purchases",money(total.lifetime_purchases))}${m("Lifetime Profit",money(total.lifetime_profit))}</div><div class="panel"><div class="section-head"><h3>Date-wise Financials</h3><input id="reportDate" type="date" value="${esc(reportDate)}"></div>${selected?`<div class="metrics">${m("Transactions",String(selected.total_transactions))}${m("Sales",money(selected.total_revenue))}${m("Cash",money(selected.cash_sales))}${m("UPI",money(selected.upi_sales))}${m("Credit",money(selected.credit_sales))}${m("Profit",money(selected.total_profit))}</div>`:`<p class="muted">Showing the latest 7 days. Search any date above for its permanent aggregate.</p><div class="table-wrap"><table><thead><tr><th>Date</th><th>Transactions</th><th>Sales</th><th>Cash</th><th>UPI</th><th>Credit</th><th>Profit</th></tr></thead><tbody>${recent.map(d=>`<tr><td>${d.business_date}</td><td>${d.total_transactions}</td><td>${money(d.total_revenue)}</td><td>${money(d.cash_sales)}</td><td>${money(d.upi_sales)}</td><td>${money(d.credit_sales)}</td><td>${money(d.total_profit)}</td></tr>`).join("")}</tbody></table></div>`}</div></section>`;
}
function workers(){return `<section class="page"><h2>Workers</h2><div class="panel"><p class="muted">Worker approval and account management stay in the existing authentication flow.</p></div></section>`}
function audit(){return `<section class="page"><h2>Audit</h2><div class="panel"><p class="muted">Audit detail is retained for 30 days, then permanently removed by the database cleanup job.</p><div class="table-wrap"><table><thead><tr><th>Date</th><th>Action</th><th>Entity</th></tr></thead><tbody>${(demo?[]:[]).map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${esc(x.action)}</td><td>${esc(x.entity_type)}</td></tr>`).join("")||'<tr><td colspan="3" class="muted">Audit records older than retention are deleted automatically.</td></tr>'}</tbody></table></div></div></section>`}
function settingsView(){return `<section class="page"><h2>Settings</h2><div class="panel"><form id="settingsForm" class="form-grid"><label>Shop name<input name="shop_name" value="${esc(settings.shop_name)}"></label><label>Timezone<input name="timezone" value="${esc(settings.timezone)}"></label><label>Currency<input name="currency" value="${esc(settings.currency)}"></label><label>Workers can modify selling price<select name="workers_can_modify_selling_price"><option value="false" ${!settings.workers_can_modify_selling_price?"selected":""}>No</option><option value="true" ${settings.workers_can_modify_selling_price?"selected":""}>Yes</option></select></label><button class="primary full">Save Settings</button></form><div class="notice">Storage retention: sales 90 days · purchases 1 year · audit 30 days · zero-balance creditor detail 7 days. Permanent financial aggregates remain.</div></div></section>`}

function render(){
 if(!profile){login();return}
 app.innerHTML=shell(activeTab, "");
 const view=document.querySelector("#view")!;
 view.innerHTML=activeTab==="dashboard"?dashboard():activeTab==="sale"?sale():activeTab==="cart"?cart():activeTab==="stock"?stock():activeTab==="creditors"?creditorList():activeTab==="history"?history():activeTab==="today"?today():activeTab==="reports"?reports():activeTab==="workers"?workers():activeTab==="audit"?audit():settingsView();
 bind();
}
function bind(){
 document.querySelectorAll<HTMLElement>("[data-nav]").forEach(x=>x.addEventListener("click",()=>{activeTab=x.dataset.nav||"dashboard";render()}));
 document.querySelector("#logout")?.addEventListener("click",async()=>{if(!demo)await supabase?.auth.signOut();profile=null;demo=false;activeTab="dashboard";login()});
 document.querySelector("#refresh")?.addEventListener("click",async()=>{await loadData();render()});
 if(activeTab==="sale")bindSale();
 if(activeTab==="cart")bindCart();
 if(activeTab==="creditorList")bindCreditors();
 if(activeTab==="history"){document.querySelectorAll("[data-history]").forEach(x=>x.addEventListener("click",()=>{historyType=(x as HTMLElement).dataset.history!;reportDate="";render()}));document.querySelectorAll("[data-range]").forEach(x=>x.addEventListener("click",()=>{historyRange=(x as HTMLElement).dataset.range!;if(historyRange!=="date")reportDate="";render()}));document.querySelector("#historyDate")?.addEventListener("change",e=>{reportDate=(e.currentTarget as HTMLInputElement).value;render()})}
 if(activeTab==="reports")document.querySelector("#reportDate")?.addEventListener("change",e=>{reportDate=(e.target as HTMLInputElement).value;render()});
 if(activeTab==="stock")document.querySelector("#addPurchase")?.addEventListener("click",purchaseForm);
 if(activeTab==="settings")document.querySelector("#settingsForm")?.addEventListener("submit",saveSettings);
}
function bindSale(){
 const f=document.querySelector<HTMLFormElement>("#saleForm")!,sel=f.elements.namedItem("product") as HTMLSelectElement,qty=f.elements.namedItem("qty") as HTMLInputElement,price=f.elements.namedItem("price") as HTMLInputElement,unit=f.elements.namedItem("unit") as HTMLSelectElement,mode=f.elements.namedItem("mode") as HTMLSelectElement;
 const update=()=>{const p=products.find(x=>x.id===sel.value);if(!p)return;price.value=String(p.selling_price_per_base_unit);unit.value=p.unit_type==="piece"?"piece":"grams";document.querySelectorAll("#saleProducts .product-card").forEach(x=>x.classList.toggle("selected",(x as HTMLElement).dataset.product===p.id));const n=Number(qty.value)||0,base=p.unit_type==="piece"?n:unit.value==="kg"?n*1000:n,total=base*p.selling_price_per_base_unit;document.querySelector("#saleTotal")!.textContent="Total: "+money(total);if(mode.value==="cash"){(f.elements.namedItem("cash") as HTMLInputElement).value=total.toFixed(2)}if(mode.value==="upi"){(f.elements.namedItem("upi") as HTMLInputElement).value=total.toFixed(2)}};
 sel.addEventListener("change",update);qty.addEventListener("input",update);price.addEventListener("input",update);unit.addEventListener("change",update);
 document.querySelectorAll<HTMLElement>("[data-product]").forEach(x=>x.addEventListener("click",()=>{sel.value=x.dataset.product!;update()}));
 document.querySelector("#saleSearch")?.addEventListener("input",e=>{const q=(e.target as HTMLInputElement).value.toLowerCase();document.querySelectorAll<HTMLElement>(".product-card").forEach(x=>x.classList.toggle("hidden",!x.textContent!.toLowerCase().includes(q)))});mode.addEventListener("change",()=>{const v=mode.value,sp=v==="split"||v==="credit_split",cr=v==="credit"||v==="credit_split";["cashBox","upiBox"].forEach(id=>document.querySelector("#"+id)?.classList.toggle("hidden",!sp));document.querySelector("#creditBox")?.classList.toggle("hidden",v!=="credit_split");document.querySelector("#creditorBox")?.classList.toggle("hidden",!cr);update()});update();
 f.addEventListener("submit",async e=>{e.preventDefault();const p=products.find(x=>x.id===sel.value)!;const n=Number(qty.value),base=p.unit_type==="piece"?n:unit.value==="kg"?n*1000:n,total=base*Number(price.value),v=mode.value;let cash=Number((f.elements.namedItem("cash") as HTMLInputElement).value)||0,upi=Number((f.elements.namedItem("upi") as HTMLInputElement).value)||0,credit=Number((f.elements.namedItem("credit") as HTMLInputElement).value)||0;const cr=(f.elements.namedItem("creditor") as HTMLSelectElement).value||null;if(!n||base<=0||base>p.current_stock_base)return notify("Invalid quantity or insufficient stock.","error");if(v==="cash"){cash=total;upi=0;credit=0}if(v==="upi"){cash=0;upi=total;credit=0}if(v==="credit"){cash=0;upi=0;credit=total}if(v==="split"&&Math.abs(cash+upi-total)>.01)return notify("Cash + UPI must equal total.","error");if(v==="credit_split"&&(credit<=0||Math.abs(cash+upi+credit-total)>.01))return notify("Cash + UPI + Credit must equal total.","error");if((v==="credit"||v==="credit_split")&&!cr)return notify("Select a creditor.","error");try{await saveSale({product_id:p.id,quantity_base:base,quantity_display:n,sold_unit:unit.value,selling_price_per_base_unit:Number(price.value)},v,cash,upi,credit,cr);notify("Sale completed.","success");await loadData();activeTab="dashboard";render()}catch(err){notify(err instanceof Error?err.message:String(err),"error")}})}
function bindCart(){
 const add=document.querySelector<HTMLFormElement>("#cartAdd");
 if(add){const sel=add.elements.namedItem("product") as HTMLSelectElement,qty=add.elements.namedItem("qty") as HTMLInputElement,unit=add.elements.namedItem("unit") as HTMLSelectElement,price=add.elements.namedItem("price") as HTMLInputElement;
  const update=()=>{const p=products.find(x=>x.id===sel.value);if(p){price.value=String(p.selling_price_per_base_unit);unit.value=p.unit_type==="piece"?"piece":"grams"}};
  sel.addEventListener("change",update);update();
  add.addEventListener("submit",e=>{e.preventDefault();const p=products.find(x=>x.id===sel.value)!;const n=Number(qty.value),base=p.unit_type==="piece"?n:unit.value==="kg"?n*1000:n;if(!n||base>p.current_stock_base)return notify("Invalid quantity or insufficient stock.","error");cartItems.push({product_id:p.id,quantity_base:base,quantity_display:n,sold_unit:unit.value,selling_price_per_base_unit:Number(price.value)});render()});
 }
 document.querySelectorAll<HTMLButtonElement>(".del-cart").forEach(b=>b.addEventListener("click",()=>{cartItems.splice(Number(b.dataset.i),1);render()}));
 document.querySelectorAll<HTMLButtonElement>(".edit-cart").forEach(b=>b.addEventListener("click",()=>{const i=Number(b.dataset.i),x=cartItems[i],q=Number(prompt("Quantity",String(x.quantity_display)));if(!q||q<=0)return;const p=products.find(p=>p.id===x.product_id)!;const base=p.unit_type==="piece"?q:x.sold_unit==="kg"?q*1000:q;if(base>p.current_stock_base)return notify("Insufficient stock.","error");x.quantity_display=q;x.quantity_base=base;render()}));
 const pay=document.querySelector<HTMLFormElement>("#cartPay");
 if(pay){const mode=pay.elements.namedItem("mode") as HTMLSelectElement,cash=pay.elements.namedItem("cash") as HTMLInputElement,upi=pay.elements.namedItem("upi") as HTMLInputElement,credit=pay.elements.namedItem("credit") as HTMLInputElement;
  const total=cartItems.reduce((a,x)=>a+x.quantity_base*x.selling_price_per_base_unit,0);
  const toggle=()=>{const v=mode.value,split=v==="split"||v==="credit_split",cr=v==="credit"||v==="credit_split";document.querySelector("#cartCashBox")?.classList.toggle("hidden",!split);document.querySelector("#cartUpiBox")?.classList.toggle("hidden",!split);document.querySelector("#cartCreditBox")?.classList.toggle("hidden",v!=="credit_split");document.querySelector("#cartCreditorBox")?.classList.toggle("hidden",!cr);if(v==="cash"){cash.value=total.toFixed(2);upi.value="0";credit.value="0"}if(v==="upi"){cash.value="0";upi.value=total.toFixed(2);credit.value="0"}if(v==="credit"){cash.value="0";upi.value="0";credit.value=total.toFixed(2)}};mode.addEventListener("change",toggle);toggle();
  pay.addEventListener("submit",async e=>{e.preventDefault();if(!cartItems.length)return notify("Add items first.","error");let c=Number(cash.value)||0,u=Number(upi.value)||0,cr=Number(credit.value)||0;if(mode.value==="cash"){c=total;u=0;cr=0}if(mode.value==="upi"){c=0;u=total;cr=0}if(mode.value==="credit"){c=0;u=0;cr=total}if(mode.value==="split"&&Math.abs(c+u-total)>.01)return notify("Cash + UPI must equal total.","error");if(mode.value==="credit_split"&&(cr<=0||Math.abs(c+u+cr-total)>.01))return notify("Cash + UPI + Credit must equal total.","error");const crid=(pay.elements.namedItem("creditor") as HTMLSelectElement).value||null;if((mode.value==="credit"||mode.value==="credit_split")&&!crid)return notify("Select a creditor.","error");try{if(demo){for(const x of cartItems){const p=products.find(p=>p.id===x.product_id)!;p.current_stock_base-=x.quantity_base;sales.unshift({id:"s"+Date.now()+Math.random(),sold_at:new Date().toISOString(),product_id:p.id,worker_id:profile!.id,total_sale:x.quantity_base*x.selling_price_per_base_unit,gross_profit:(x.selling_price_per_base_unit-p.purchase_price_per_base_unit)*x.quantity_base,cash_amount:c* (x.quantity_base*x.selling_price_per_base_unit/total),upi_amount:u*(x.quantity_base*x.selling_price_per_base_unit/total),payment_mode:mode.value,quantity_base:x.quantity_base,quantity_display:x.quantity_display,sold_unit:x.sold_unit,voided:false,products:{name:p.name},profiles:{full_name:profile!.full_name}})}if(cr>0&&crid)ledger.unshift({id:"l"+Date.now(),creditor_id:crid,type:"credit_sale",amount:cr,payment_mode:mode.value,created_at:new Date().toISOString(),worker_id:profile!.id,profiles:{full_name:profile!.full_name}})}else{const r=await supabase!.rpc("complete_cart_sale",{p_worker_id:profile!.id,p_items:cartItems,p_payment_mode:mode.value,p_cash_amount:c,p_upi_amount:u,p_credit_amount:cr,p_creditor_id:crid});if(r.error)throw r.error}cartItems=[];notify("Cart sale completed.","success");await loadData();render()}catch(err){notify(err instanceof Error?err.message:String(err),"error")}})
 }
}
function bindCreditors(){
 document.querySelector("#creditSearch")?.addEventListener("input",e=>{const q=(e.target as HTMLInputElement).value.toLowerCase();document.querySelectorAll<HTMLElement>(".credit-row").forEach(x=>x.style.display=(x.dataset.q||"").includes(q)?"":"none")});
 document.querySelector("#newCreditor")?.addEventListener("click",async()=>{const n=prompt("Creditor name"),m=prompt("Mobile");if(!n?.trim())return;if(demo){creditorList.push({id:"c"+Date.now(),name:n.trim(),mobile:m?.trim()||""});render();return}const r=await supabase!.rpc("get_or_create_creditor",{p_name:n.trim(),p_mobile:m?.trim()||""});if(r.error)notify(r.error.message,"error");else{await loadData();render()}});
 document.querySelectorAll<HTMLButtonElement>(".pay-credit").forEach(b=>b.addEventListener("click",async()=>{const id=b.dataset.id!,bal=qBalance(id);const amount=Number(prompt("Payment amount. Outstanding: "+money(bal)));if(!amount||amount<=0||amount>bal)return notify("Enter an amount up to the outstanding balance.","error");const mode=(prompt("Payment mode: cash, upi, split","cash")||"cash").toLowerCase();let cash=0,upi=0;if(mode==="cash")cash=amount;else if(mode==="upi")upi=amount;else if(mode==="split"){cash=Number(prompt("Cash amount","0"));upi=amount-cash}else return notify("Invalid payment mode.","error");try{if(demo)ledger.unshift({id:"l"+Date.now(),creditor_id:id,type:"payment_received",amount,payment_mode:mode,cash_amount:cash,upi_amount:upi,created_at:new Date().toISOString(),worker_id:profile!.id,profiles:{full_name:profile!.full_name}});else{const r=await supabase!.rpc("receive_credit_payment",{p_creditor_id:id,p_amount:amount,p_payment_mode:mode,p_cash_amount:cash,p_upi_amount:upi});if(r.error)throw r.error}await loadData();render()}catch(err){notify(err instanceof Error?err.message:String(err),"error")}}));
 document.querySelectorAll<HTMLButtonElement>(".credit-history").forEach(b=>b.addEventListener("click",()=>{const id=b.dataset.id!,c=creditorList.find(x=>x.id===id),rows=ledger.filter(x=>x.creditor_id===id);document.querySelector("#creditDetail")!.innerHTML=`<div class="panel"><div class="section-head"><h3>${esc(c?.name)} · ${money(qBalance(id))} outstanding</h3><button id="closeCredit" class="ghost">Close</button></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Mode</th><th>By</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td>${esc(x.payment_mode||"")}</td><td>${esc(x.profiles?.full_name||"")}</td></tr>`).join("")}</tbody></table></div></div>`;document.querySelector("#closeCredit")?.addEventListener("click",()=>document.querySelector("#creditDetail")!.innerHTML="")}));
}
function purchaseForm(){
 const h=document.querySelector("#purchaseForm")!;h.innerHTML=`<div class="panel"><h3>Record Purchase</h3><form id="purchaseFormInner" class="form-grid"><label>Product<select name="product">${products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}</select></label><label>Quantity<input name="qty" type="number" min="0.001" step=".001" required></label><label>Purchase price<input name="price" type="number" min="0" step=".01" required></label><button class="primary full">Save Purchase</button></form></div>`;const f=document.querySelector<HTMLFormElement>("#purchaseFormInner")!;f.addEventListener("submit",async e=>{e.preventDefault();const p=products.find(x=>x.id===(f.elements.namedItem("product") as HTMLSelectElement).value)!,q=Number((f.elements.namedItem("qty") as HTMLInputElement).value),pr=Number((f.elements.namedItem("price") as HTMLInputElement).value);if(!q||q<=0)return;if(demo){p.current_stock_base+=q;p.purchase_price_per_base_unit=pr;purchases.unshift({id:"q"+Date.now(),product_id:p.id,product_name_snapshot:p.name,quantity_base:q,quantity_display:q,purchase_unit:p.unit_type,total_cost:q*pr,purchase_price_per_base_unit:pr,purchased_at:new Date().toISOString(),profiles:{full_name:profile!.full_name}});notify("Purchase saved.","success");render();return}const ins=await supabase!.from("inventory_purchases").insert({product_id:p.id,product_name_snapshot:p.name,quantity_base:q,quantity_display:q,purchase_unit:p.unit_type,purchase_price_per_base_unit:pr,total_cost:q*pr,purchased_by:profile!.id});if(ins.error)return notify(ins.error.message,"error");const up=await supabase!.from("products").update({current_stock_base:Number(p.current_stock_base)+q,purchase_price_per_base_unit:pr}).eq("id",p.id);if(up.error)return notify(up.error.message,"error");await loadData();render()})}

async function saveSettings(e:Event){e.preventDefault();const f=e.currentTarget as HTMLFormElement,fd=new FormData(f);const next={shop_name:String(fd.get("shop_name")),timezone:String(fd.get("timezone")),currency:String(fd.get("currency")),workers_can_modify_selling_price:fd.get("workers_can_modify_selling_price")==="true"};if(demo){settings={...settings,...next};notify("Settings saved.","success");render();return}const r=await supabase!.from("shop_settings").update(next).eq("id",1);if(r.error)return notify(r.error.message,"error");settings={...settings,...next};notify("Settings saved.","success");render()}

function login(msg=""){
 app.innerHTML=`<div class="login"><div class="login-card"><div class="brand big">SHOP MANAGEMENT</div><h2>Storage Redesign Test</h2><p class="muted">Use the demo to test the complete redesigned UI without Supabase.</p>${msg?`<div class="notice danger">${esc(msg)}</div>`:""}<button id="demoBtn" class="primary wide">🧪 Test Demo App</button><div class="divider">OR</div><form id="realLogin"><label>Supabase Project URL<input name="url" placeholder="https://xxxxx.supabase.co"></label><label>Publishable key<input name="key" placeholder="sb_publishable_..."></label><label>Email<input name="email" type="email"></label><label>Password<input name="password" type="password"></label><button class="ghost wide">Connect & Sign In</button></form><p class="tiny">This branch is isolated from production. Demo data is temporary and never writes to Supabase.</p></div></div>`;
 document.querySelector("#demoBtn")?.addEventListener("click",async()=>{demo=true;const d=demoClient();profile=d.owner;settings={shop_name:"Demo Grocery Store",currency:"INR",timezone:"Asia/Kolkata",workers_can_modify_selling_price:true};activeTab="dashboard";await loadData();render()});
 document.querySelector<HTMLFormElement>("#realLogin")?.addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),url=String(fd.get("url")||"").trim(),key=String(fd.get("key")||"").trim(),email=String(fd.get("email")||"").trim(),password=String(fd.get("password")||"");if(!url||!key||!email||!password)return notify("Fill all fields.","error");supabase=createClient(url,key);const r=await supabase.auth.signInWithPassword({email,password});if(r.error)return login(r.error.message);localStorage.setItem(URL_KEY,url);localStorage.setItem(KEY_KEY,key);const p=await supabase.from("profiles").select("*").eq("id",r.data.user.id).single();if(p.error)return login(p.error.message);const prof=p.data as Profile;profile=prof;if(!prof.is_active)return login("Your account is awaiting approval.");await loadData();render()});
 const c=readConn();if(c.url&&c.key){(document.querySelector('input[name="url"]') as HTMLInputElement).value=c.url;(document.querySelector('input[name="key"]') as HTMLInputElement).value=c.key}
}
connect();login();
