import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { Capacitor } from "@capacitor/core";
import { ShopDownloads } from "@shop-management/downloads";
import "./styles.css";

type Role="owner"|"worker";
type Profile={id:string;full_name:string;email:string;role:Role;is_active:boolean;shop_id?:string};
type Product={id:string;name:string;unit_type:"piece"|"weight";current_stock_base:number;purchase_price_per_base_unit:number;selling_price_per_base_unit:number;low_stock_threshold_base:number;is_active:boolean};
type AnyRow=Record<string,any>;

const URL_KEY="shop_management_supabase_url", KEY_KEY="shop_management_supabase_publishable_key";
let supabase:SupabaseClient|null=null, profile:Profile|null=null;
let settings:any={shop_name:"My Shop",currency:"INR",timezone:"Asia/Kolkata",workers_can_modify_selling_price:false,allow_below_cost_sales:true,allow_zero_price_sales:true,dashboard_reset_time:"00:00"};
let products:Product[]=[], sales:AnyRow[]=[], purchases:AnyRow[]=[], creditors:AnyRow[]=[], ledger:AnyRow[]=[], debtors:AnyRow[]=[], debtorLedger:AnyRow[]=[], daily:AnyRow[]=[], auditRows:AnyRow[]=[], workersRows:Profile[]=[], lifetime:any={};
let demo=false, demoReady=false, activeTab="dashboard", historyType="sales", historyRange="today", historyDate="", reportDate="", purchaseDate="", auditDate="";
let bottomNavScrollLeft=0;
let cartItems:AnyRow[]=[], returnsRows:AnyRow[]=[];
const app=document.querySelector<HTMLDivElement>("#app")!;

const m=(l:string,v:string)=>'<div class="metric"><span>'+l+'</span><b>'+v+'</b></div>';
const money=(n:any)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:settings.currency||"INR",maximumFractionDigits:2}).format(Number(n)||0);
const esc=(s:any)=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const downloadText=async(fileName:string,content:string)=>{
 try{
  if(Capacitor.isNativePlatform()){await ShopDownloads.saveTextToDownloads({fileName,content});notify("Saved to Android Downloads.","success");return}
 }catch(e){notify(e instanceof Error?e.message:"Android download failed; using browser download.","error")}
 const blob=new Blob([content],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");
 a.href=url;a.download=fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
};
const localDate=(d=new Date())=>new Intl.DateTimeFormat("en-CA",{timeZone:settings.timezone||"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(d); const businessDate=(d=new Date())=>{const a=new Intl.DateTimeFormat("en-GB",{timeZone:settings.timezone||"Asia/Kolkata",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(d),hh=Number(a.find(x=>x.type==="hour")?.value||0),mm=Number(a.find(x=>x.type==="minute")?.value||0),r=String(settings.dashboard_reset_time||"00:00").split(":").map(Number),x=(hh<r[0]||(hh===r[0]&&mm<r[1]))?new Date(d.getTime()-86400000):d;return localDate(x)};
const fmt=(d:any)=>d?new Date(d).toLocaleString("en-IN",{dateStyle:"short",timeStyle:"short"}):"";
const notify=(m:string,t="info")=>{const x=document.createElement("div");x.className="toast "+t;x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)};
const readConn=()=>({url:localStorage.getItem(URL_KEY)||"",key:localStorage.getItem(KEY_KEY)||""});
const connect=()=>{const c=readConn();if(c.url&&c.key){supabase=createClient(c.url,c.key);return true}return false};
const daysAgo=(n:number,h=12)=>{const d=new Date();d.setDate(d.getDate()-n);d.setHours(h,15,0,0);return d.toISOString()};

function buildDemo(){
 const owner:Profile={id:"demo-owner",full_name:"Demo Owner",email:"owner@demo.shop",role:"owner",is_active:true,shop_id:"SHOP-DEMO0001"};
 const worker:Profile={id:"demo-worker",full_name:"Demo Worker",email:"worker@demo.shop",role:"worker",is_active:true,shop_id:"SHOP-DEMO0001"};
 const ps:Product[]=[
  {id:"p1",name:"Tata Salt 1kg",unit_type:"piece",current_stock_base:62,purchase_price_per_base_unit:24,selling_price_per_base_unit:30,low_stock_threshold_base:12,is_active:true},
  {id:"p2",name:"Aashirvaad Atta 5kg",unit_type:"piece",current_stock_base:28,purchase_price_per_base_unit:210,selling_price_per_base_unit:255,low_stock_threshold_base:8,is_active:true},
  {id:"p3",name:"Fortune Oil 1L",unit_type:"piece",current_stock_base:35,purchase_price_per_base_unit:112,selling_price_per_base_unit:135,low_stock_threshold_base:10,is_active:true},
  {id:"p4",name:"Toor Dal 1kg",unit_type:"piece",current_stock_base:11,purchase_price_per_base_unit:118,selling_price_per_base_unit:145,low_stock_threshold_base:12,is_active:true},
  {id:"p5",name:"Basmati Rice 5kg",unit_type:"piece",current_stock_base:9,purchase_price_per_base_unit:410,selling_price_per_base_unit:475,low_stock_threshold_base:8,is_active:true},
  {id:"p6",name:"Sugar 1kg",unit_type:"piece",current_stock_base:42,purchase_price_per_base_unit:42,selling_price_per_base_unit:50,low_stock_threshold_base:10,is_active:true},
  {id:"p7",name:"Moong Dal 1kg",unit_type:"weight",current_stock_base:18500,purchase_price_per_base_unit:110,selling_price_per_base_unit:135,low_stock_threshold_base:5000,is_active:true},
  {id:"p8",name:"Tea 250g",unit_type:"piece",current_stock_base:26,purchase_price_per_base_unit:92,selling_price_per_base_unit:120,low_stock_threshold_base:8,is_active:true}
 ];
 const cr=[{id:"c1",name:"Rahul Sharma",mobile:"9876543210"},{id:"c2",name:"Priya Traders",mobile:"9123456780"},{id:"c3",name:"Amit Verma",mobile:"9988776655"}];
 const db=[{id:"d1",name:"Sharma Wholesale",mobile:"9000000001"},{id:"d2",name:"City Distributors",mobile:"9000000002"}];
 const sales:AnyRow[]=[]; const pur:AnyRow[]=[]; const lg:AnyRow[]=[]; const dlg:AnyRow[]=[]; const ds:AnyRow[]=[]; const audits:AnyRow[]=[];
 const modes=["cash","upi","split","credit"];
 for(let i=0;i<365;i++){
   const date=new Date();date.setDate(date.getDate()-i);date.setHours(10+(i%8),20,0,0);
   const count=i<90?3+(i%5):0;
   let revenue=0,profit=0,cash=0,upi=0,credit=0;
   if(i<90){
     for(let j=0;j<count;j++){
       const p=ps[(i+j)%ps.length], qty=p.unit_type==="weight"?500+(j*250):1+(j%3);
       const total=qty*(p.unit_type==="weight"?p.selling_price_per_base_unit/1000:p.selling_price_per_base_unit);
       const gp=total-(qty*(p.unit_type==="weight"?p.purchase_price_per_base_unit/1000:p.purchase_price_per_base_unit));
       const mode=modes[(i+j)%modes.length];
       const ca=mode==="cash"?total:mode==="split"?Math.round(total*.45):0;
       const up=mode==="upi"?total:mode==="split"?total-ca:0;
       const crv=mode==="credit"?total:0;
       sales.push({id:"ds"+i+"-"+j,sold_at:date.toISOString(),product_id:p.id,product_name_snapshot:p.name,worker_id:j%2?worker.id:owner.id,quantity_base:p.unit_type==="weight"?qty:qty,quantity_display:qty,sold_unit:p.unit_type==="weight"?"grams":"piece",selling_price_per_base_unit:p.selling_price_per_base_unit,total_sale:total,gross_profit:gp,cash_amount:ca,upi_amount:up,credit_amount:crv,payment_mode:mode,voided:false,transaction_id:"tx"+i+"-"+j,products:{name:p.name},profiles:{full_name:j%2?"Demo Worker":"Demo Owner"}});
       revenue+=total;profit+=gp;cash+=ca;upi+=up;credit+=crv;
       if(crv>0)lg.push({id:"cl"+i+"-"+j,creditor_id:cr[(i+j)%cr.length].id,type:"credit_sale",amount:crv,payment_mode:"credit",created_at:date.toISOString(),worker_id:worker.id,profiles:{full_name:"Demo Worker"}});
     }
   } else {
     revenue=1500+(i%9)*275;profit=Math.round(revenue*.16);cash=Math.round(revenue*.42);upi=revenue-cash;credit=0;
   }
   ds.push({shop_id:owner.shop_id,business_date:localDate(date),total_transactions:count||Math.max(1,2+(i%3)),total_revenue:revenue,total_profit:profit,cash_sales:cash,upi_sales:upi,credit_sales:credit,cash_profit:Math.round(profit*(cash/Math.max(revenue,1))),upi_profit:Math.round(profit*(upi/Math.max(revenue,1))),credit_profit:Math.round(profit*(credit/Math.max(revenue,1))),creditor_amount:credit,purchase_cash:0,purchase_upi:0,purchase_credit:0,total_purchases:0,debtor_payment_cash:0,debtor_payment_upi:0,debtor_payment_total:0});
   if(i<365){
     const pd=new Date(date);pd.setHours(8,10,0,0);
     const p=ps[i%ps.length], qty=p.unit_type==="weight"?2500+(i%5)*500:10+(i%7), cost=qty*(p.unit_type==="weight"?p.purchase_price_per_base_unit/1000:p.purchase_price_per_base_unit), mode=i%4===0?"credit":i%3===0?"split":i%2?"upi":"cash";
     const pc=mode==="cash"?cost:mode==="split"?cost*.5:0, pu=mode==="upi"?cost:mode==="split"?cost*.5:0, pcr=mode==="credit"?cost:0;
     const debtor=pcr>0?db[i%db.length]:null;
     pur.push({id:"dp"+i,product_id:p.id,product_name_snapshot:p.name,quantity_base:p.unit_type==="weight"?qty:qty,quantity_display:qty,purchase_unit:p.unit_type,purchase_price_per_base_unit:p.purchase_price_per_base_unit,total_cost:cost,purchased_at:pd.toISOString(),purchased_by:i%2?worker.id:owner.id,profiles:{full_name:i%2?"Demo Worker":"Demo Owner"},payment_mode:mode,cash_amount:pc,upi_amount:pu,credit_amount:pcr,credit_paid:0,pre_stock:false,supplier_name:pcr>0?debtor?.name:"",debtor_id:debtor?.id||null});
     if(pcr>0&&debtor)dlg.push({id:"dp-ledger-"+i,debtor_id:debtor.id,type:"credit_purchase",amount:pcr,payment_mode:"credit",cash_amount:0,upi_amount:0,created_at:pd.toISOString(),worker_id:i%2?worker.id:owner.id,profiles:{full_name:i%2?"Demo Worker":"Demo Owner"}});
     const row=ds[ds.length-1];row.purchase_cash=pc;row.purchase_upi=pu;row.purchase_credit=pcr;row.total_purchases=cost;
   }
   if(i<30) audits.push({id:"a"+i,created_at:date.toISOString(),actor_id:i%2?worker.id:owner.id,action:i%3?"sale_created":"purchase_created",entity_type:i%3?"sale":"purchase",profiles:{full_name:i%2?"Demo Worker":"Demo Owner"}});
 }
 // Add explicit pre-stock records: these never appear in Purchase History or financial purchase reports.
 for(let i=0;i<18;i++){const p=ps[i%ps.length];pur.push({id:"pre"+i,product_id:p.id,product_name_snapshot:p.name,quantity_base:20,quantity_display:20,purchase_unit:p.unit_type,purchase_price_per_base_unit:p.purchase_price_per_base_unit,total_cost:20*p.purchase_price_per_base_unit,purchased_at:daysAgo(20+i),purchased_by:owner.id,profiles:{full_name:"Demo Owner"},payment_mode:"pre_stock",cash_amount:0,upi_amount:0,credit_amount:0,pre_stock:true,supplier_name:"Opening Stock"});}
 for(const c of cr){lg.push({id:"pay"+c.id,creditor_id:c.id,type:"payment_received",amount:c.id==="c1"?1800:650,payment_mode:c.id==="c1"?"split":"upi",cash_amount:c.id==="c1"?900:0,upi_amount:c.id==="c1"?900:650,created_at:daysAgo(2),worker_id:owner.id,profiles:{full_name:"Demo Owner"}});}
 dlg.push({id:"dpay1",debtor_id:"d1",type:"payment_made",amount:900,payment_mode:"upi",cash_amount:0,upi_amount:900,created_at:daysAgo(1),worker_id:owner.id,profiles:{full_name:"Demo Owner"}});
 const paidDate=localDate(new Date(Date.now()-864e5));const paidRow=ds.find(x=>x.business_date===paidDate);if(paidRow){paidRow.debtor_payment_total=900;paidRow.debtor_payment_upi=900;}
 return {owner,worker,products:ps,sales,purchases:pur,creditors:cr,ledger:lg,debtors:db,debtorLedger:dlg,daily:ds,audit:audits,workers:[owner,worker],lifetime:{lifetime_sales:ds.reduce((a,x)=>a+Number(x.total_revenue||0),0),lifetime_purchases:pur.reduce((a,x)=>a+Number(x.total_cost||0),0),lifetime_profit:ds.reduce((a,x)=>a+Number(x.total_profit||0),0)}};
}

let demoData:ReturnType<typeof buildDemo>|null=null;
function initDemo(){if(!demoData)demoData=buildDemo();const d=demoData;products=d.products;sales=d.sales;purchases=d.purchases;creditors=d.creditors;ledger=d.ledger;debtors=d.debtors;debtorLedger=d.debtorLedger;daily=d.daily;auditRows=d.audit;workersRows=d.workers;lifetime=d.lifetime;settings={shop_name:"Demo Grocery Store",currency:"INR",timezone:"Asia/Kolkata",workers_can_modify_selling_price:true,allow_below_cost_sales:true,allow_zero_price_sales:true,dashboard_reset_time:"00:00"};profile=d.owner;demo=true;demoReady=true}
function qBalance(id:string){return ledger.filter(x=>x.creditor_id===id).reduce((a,x)=>a+(x.type==="credit_sale"||x.type==="adjustment"?Number(x.amount):x.type==="payment_received"?-Number(x.amount):0),0)}
function dBalance(id:string){return debtorLedger.filter(x=>x.debtor_id===id).reduce((a,x)=>a+(x.type==="credit_purchase"||x.type==="adjustment"?Number(x.amount):x.type==="payment_made"?-Number(x.amount):0),0)}
function currentSales(){const today=businessDate();return sales.filter(s=>!s.voided&&businessDate(new Date(s.sold_at))===today)}
function currentStats(){const a=currentSales();return {tx:new Set(a.map(x=>x.transaction_id||x.id)).size,sales:a.reduce((x,y)=>x+Number(y.total_sale||0),0),profit:a.reduce((x,y)=>x+Number(y.gross_profit||0),0),cash:a.reduce((x,y)=>x+Number(y.cash_amount||0),0),upi:a.reduce((x,y)=>x+Number(y.upi_amount||0),0),credit:a.reduce((x,y)=>x+Number(y.credit_amount||0),0)}}

async function loadData(){
 if(demo){if(!demoReady)initDemo();return}
 if(!supabase||!profile)return;
 const [set,p,s,q,c,l,db,dl,df,life,au,rr,wr]=await Promise.all([
  supabase.from("shop_settings").select("*").limit(1).maybeSingle(),
  supabase.from("products").select("*").eq("is_active",true).order("name"),
  supabase.from("sales").select("*,products(name),profiles:worker_id(full_name)").order("sold_at",{ascending:false}).limit(1000),
  supabase.from("inventory_purchases").select("*,profiles:purchased_by(full_name)").order("purchased_at",{ascending:false}).limit(1000),
  supabase.from("creditors").select("*").order("name"),
  supabase.from("credit_ledger").select("*,profiles:worker_id(full_name)").order("created_at",{ascending:false}).limit(2000),
  supabase.from("debtors").select("*").order("name"),
  supabase.from("debtor_ledger").select("*,profiles:worker_id(full_name)").order("created_at",{ascending:false}).limit(2000),
  supabase.from("daily_financial_summaries").select("*").order("business_date",{ascending:false}).limit(400),
  supabase.from("lifetime_financial_summaries").select("*").limit(1).maybeSingle(),
  supabase.from("audit_logs").select("*,profiles:actor_id(full_name)").order("created_at",{ascending:false}).limit(1000),
  supabase.from("returns").select("*,products(name),profiles:returned_by(full_name)").order("returned_at",{ascending:false}).limit(1000),
  supabase.from("profiles").select("*").order("full_name")
 ]);
 if(set.data)settings={...settings,...set.data};
 products=p.data||[];sales=s.data||[];purchases=q.data||[];creditors=c.data||[];ledger=l.data||[];debtors=db.data||[];debtorLedger=dl.data||[];daily=df.data||[];lifetime=life.data||{lifetime_sales:0,lifetime_purchases:0,lifetime_profit:0};auditRows=au.data||[];workersRows=(wr.data||[]).map((x:any)=>({...x,role:x.role as Role}));
}

function shell(title:string){
 const owner=profile?.role==="owner";
 const nav:[string,string][]=[["dashboard","Dashboard"],["sale","Add Sale"],["cart","Cart"],["stock","Stock"],["returns","Returns"],["creditors","Creditors"],["debtors","Debtors"],["history","History"]];
 if(owner) nav.push(["today","Today Stats"],["reports","Reports"],["workers","Workers"],["audit","Audit"],["settings","Settings"]);
 return '<div class="app-shell"><header><div><b>'+esc(settings.shop_name)+'</b><span class="muted">'+esc(title)+'</span></div><button id="logout" class="ghost small">Sign out</button></header><main><div id="view"></div></main><nav class="bottom-nav">'+nav.map(([id,n])=>'<button data-nav="'+id+'" class="'+(activeTab===id?"active":"")+'">'+esc(n)+'</button>').join("")+'</nav></div>';
}

function dashboard(){
 const s=currentStats(),low=products.filter(p=>Number(p.current_stock_base)<=Number(p.low_stock_threshold_base));
 return '<section class="page"><div class="page-head"><div><h2>Dashboard</h2><p class="muted">Quick actions and stock overview.</p></div><button id="refresh" class="ghost">↻ Refresh</button></div><div class="metrics">'+m("Today Sales",money(s.sales))+m("Today Profit",money(s.profit))+m("Cash",money(s.cash))+m("UPI",money(s.upi))+m("Credit",money(s.credit))+'</div><div class="quick-grid"><button data-nav="sale">＋ Add Sale</button><button data-nav="cart">🛒 Cart</button><button data-nav="stock">Stock</button><button data-nav="creditors">Creditors</button></div><div class="panel"><div class="section-head"><h3>Stock</h3><span class="badge">'+products.length+' products</span></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Stock</th><th>Sell</th><th>Status</th></tr></thead><tbody>'+products.map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+p.current_stock_base+' '+(p.unit_type==="piece"?"pcs":"g")+'</td><td>'+money(p.selling_price_per_base_unit)+'</td><td>'+(Number(p.current_stock_base)<=Number(p.low_stock_threshold_base)?'<span class="badge warn">LOW</span>':'<span class="badge ok">OK</span>')+'</td></tr>').join("")+'</tbody></table></div>'+(low.length?'<div class="notice warning">'+low.length+' product(s) are low in stock.</div>':"")+'</div></section>';
}

function sale(){
 return '<section class="page"><div class="page-head"><div><h2>Add Sale</h2><p class="muted">Search and select any product.</p></div></div><div class="panel"><div class="search-row"><input id="saleSearch" placeholder="Search product..."><button id="saleSearchBtn" class="ghost">Search</button></div><div id="saleProducts" class="product-grid"></div><form id="saleForm" class="form-grid"><label>Product<select name="product" required>'+products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join("")+'</select></label><label>Quantity<input name="qty" type="number" min="0.001" step="0.001" value="1" required></label><label>Unit<select name="unit"><option value="piece">pieces</option><option value="grams">grams</option><option value="kg">kg</option></select></label><label>Selling price<input name="price" type="number" step=".01" min="0" required></label><label>Payment<select name="mode"><option value="cash">Cash</option><option value="upi">UPI</option><option value="split">Cash + UPI</option><option value="credit">Credit</option><option value="credit_split">Credit + Cash + UPI</option></select></label><label id="cashBox" class="hidden">Cash<input name="cash" type="number" step=".01" min="0" value="0"></label><label id="upiBox" class="hidden">UPI<input name="upi" type="number" step=".01" min="0" value="0"></label><label id="creditBox" class="hidden">Credit<input name="credit" type="number" step=".01" min="0" value="0"></label><label id="creditorBox" class="hidden">Creditor<select name="creditor"><option value="">Select creditor</option>'+creditors.map(c=>'<option value="'+c.id+'">'+esc(c.name)+' — '+esc(c.mobile)+'</option>').join("")+'<option value="__new__">＋ New Creditor</option></select></label><div class="full notice" id="saleTotal">Total: ₹0.00</div><button class="primary full">Complete Sale</button></form></div></section>';
}

function cart(){
 const total=cartItems.reduce((a,x)=>a+Number(x.quantity_base)*Number(x.selling_price_per_base_unit),0);
 return '<section class="page"><div class="page-head"><h2>Cart</h2><span class="badge">'+cartItems.length+' item(s)</span></div><div class="panel"><div class="search-row"><input id="cartSearch" placeholder="Search product to add..."><button id="cartSearchBtn" class="ghost">Search</button></div><div id="cartProducts" class="product-grid"></div><form id="cartAdd" class="form-grid"><label>Product<select name="product">'+products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+' — '+p.current_stock_base+' available</option>').join("")+'</select></label><label>Quantity<input name="qty" type="number" min="0.001" step=".001" value="1"></label><label>Unit<select name="unit"><option value="piece">pieces</option><option value="grams">grams</option><option value="kg">kg</option></select></label><label>Selling price<input name="price" type="number" step=".01" min="0"></label><div class="full notice" id="cartPreview">Preview: select a product</div><button class="primary full">Add to Cart</button></form><div class="notice">Cart total: <b>'+money(total)+'</b></div>'+ (cartItems.length?'<div class="table-wrap"><table><thead><tr><th>Product</th><th>Qty</th><th>Total</th><th></th></tr></thead><tbody>'+cartItems.map((x,i)=>'<tr><td>'+esc(x.product_name_snapshot||products.find(p=>p.id===x.product_id)?.name||"")+'</td><td>'+esc(x.quantity_display)+'</td><td>'+money(Number(x.quantity_base)*Number(x.selling_price_per_base_unit))+'</td><td><button class="smallbtn edit-cart" data-i="'+i+'">Edit</button> <button class="smallbtn delete-cart" data-i="'+i+'">Delete</button></td></tr>').join("")+'</tbody></table></div>':"")+'<div class="panel"><form id="cartPay" class="form-grid"><label>Payment<select name="mode"><option value="cash">Cash</option><option value="upi">UPI</option><option value="split">Cash + UPI</option><option value="credit">Credit</option><option value="credit_split">Credit + Cash + UPI</option></select></label><label>Cash<input name="cash" type="number" step=".01" value="'+total.toFixed(2)+'"></label><label>UPI<input name="upi" type="number" step=".01" value="0"></label><label>Credit<input name="credit" type="number" step=".01" value="0"></label><label>Creditor<select name="creditor"><option value="">Select creditor</option>'+creditors.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join("")+'<option value="__new__">＋ New Creditor</option></select></label><button class="primary full" '+(cartItems.length?"":"disabled")+'>Confirm Cart Sale</button></form></div></div></section>';
}
function stock(){
 const owner=profile?.role==="owner";
 return '<section class="page"><div class="page-head"><div><h2>Stock</h2><p class="muted">Current stock and purchase actions.</p></div><div class="action-row">'+(owner?'<button id="addProduct" class="ghost">＋ Add Product</button>':"")+'<button id="addPurchase" class="primary">＋ Purchase</button></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Product</th><th>Current</th><th>Buy</th><th>Sell</th></tr></thead><tbody>'+products.map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+p.current_stock_base+' '+(p.unit_type==="piece"?"pcs":"g")+'</td><td>'+money(p.purchase_price_per_base_unit)+'</td><td>'+money(p.selling_price_per_base_unit)+'</td></tr>').join("")+'</tbody></table></div></div><div id="stockForm"></div></section>';
}

function productForm(){
 const h=document.querySelector("#stockForm")!;h.innerHTML='<div class="panel"><h3>Add Product</h3><form id="productForm" class="form-grid"><label>Product name<input name="name" required></label><label>Unit<select name="unit"><option value="piece">Piece</option><option value="weight">Weight (grams/kg)</option></select></label><label>Quantity<input name="qty" type="number" min="0" step=".001" required></label><label>Low stock threshold<input name="low" type="number" min="0" step=".001" value="5"></label><label>Purchase price<input name="purchase" type="number" min="0" step=".01" required></label><label>Sale price<input name="sale" type="number" min="0" step=".01" required></label><div class="full notice"><b>Pre-stock recording:</b> check this if the quantity is opening/pre-recorded stock and should not become purchase history or a purchase financial entry.</div><label class="check full"><input type="checkbox" name="prestock"> Pre-stock recording</label><label class="full">Payment method<select name="payment"><option value="cash">Cash</option><option value="upi">UPI</option><option value="credit">Credit</option><option value="split">Cash + UPI</option><option value="pre_stock">Pre-stock recording</option></select></label><button class="primary full">Create Product</button></form></div>';
 const f=document.querySelector<HTMLFormElement>("#productForm")!;f.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(f),name=String(fd.get("name")||"").trim(),unit=String(fd.get("unit")),q=Number(fd.get("qty")),low=Number(fd.get("low")),buy=Number(fd.get("purchase")),sell=Number(fd.get("sale")),pre=fd.get("prestock")==="on"||String(fd.get("payment"))==="pre_stock";if(!name||q<0)return notify("Enter valid product details.","error");if(demo){const p:Product={id:"p"+Date.now(),name,unit_type:unit==="piece"?"piece":"weight",current_stock_base:q,purchase_price_per_base_unit:buy,selling_price_per_base_unit:sell,low_stock_threshold_base:low,is_active:true};products.push(p);if(!pre)purchases.unshift({id:"q"+Date.now(),product_id:p.id,product_name_snapshot:name,quantity_base:q,quantity_display:q,purchase_unit:unit,total_cost:q*buy,purchase_price_per_base_unit:buy,purchased_at:new Date().toISOString(),purchased_by:profile!.id,profiles:{full_name:profile!.full_name},payment_mode:String(fd.get("payment")),cash_amount:String(fd.get("payment"))==="cash"?q*buy:0,upi_amount:String(fd.get("payment"))==="upi"?q*buy:0,credit_amount:String(fd.get("payment"))==="credit"?q*buy:0,pre_stock:false});notify("Product added.","success");render();return}const r=await supabase!.from("products").insert({name,unit_type:unit,current_stock_base:q,purchase_price_per_base_unit:buy,selling_price_per_base_unit:sell,low_stock_threshold_base:low,is_active:true}).select().single();if(r.error)return notify(r.error.message,"error");if(!pre){const total=q*buy;const mode=String(fd.get("payment"));const ins=await supabase!.from("inventory_purchases").insert({product_id:r.data.id,product_name_snapshot:name,quantity_base:q,quantity_display:q,purchase_unit:unit,purchase_price_per_base_unit:buy,total_cost:total,purchased_by:profile!.id,payment_mode:mode,cash_amount:mode==="cash"?total:mode==="split"?total/2:0,upi_amount:mode==="upi"?total:mode==="split"?total/2:0,credit_amount:mode==="credit"?total:0,pre_stock:false});if(ins.error)return notify(ins.error.message,"error")}await loadData();render()})}

function purchaseForm(){
 const h=document.querySelector("#stockForm")!;h.innerHTML='<div class="panel"><h3>Record Purchase</h3><form id="purchaseFormInner" class="form-grid"><label>Product<select name="product">'+products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join("")+'</select></label><label>Quantity<input name="qty" type="number" min=".001" step=".001" required></label><label>Purchase price<input name="price" type="number" min="0" step=".01" required></label><label>Payment method<select name="payment"><option value="cash">Cash</option><option value="upi">UPI</option><option value="credit">Debt / Credit</option><option value="split">Cash + UPI</option><option value="pre_stock">Pre-stock recording</option></select></label><label id="purchaseDebtorBox" class="hidden">Supplier credit/debtor<select name="debtor"><option value="">Select debtor</option>'+debtors.map(d=>'<option value="'+d.id+'">'+esc(d.name)+' — '+esc(d.mobile)+'</option>').join("")+'<option value="__new__">＋ New Debtor</option></select></label><label>Supplier / Notes<input name="supplier" placeholder="Optional supplier name"></label><label class="check full"><input type="checkbox" name="prestock"> Pre-stock recording</label><div class="full notice">Purchase, stock, payment split and supplier credit are saved atomically.</div><button class="primary full">Save Purchase</button></form></div>';
 const f=document.querySelector<HTMLFormElement>("#purchaseFormInner")!,mode=f.elements.namedItem("payment") as HTMLSelectElement,pre=f.elements.namedItem("prestock") as HTMLInputElement,db=f.elements.namedItem("debtor") as HTMLSelectElement;const sync=()=>{const c=mode.value==="credit";document.querySelector("#purchaseDebtorBox")?.classList.toggle("hidden",!c);if(mode.value==="pre_stock"){pre.checked=true;pre.disabled=true}else pre.disabled=false};mode.addEventListener("change",sync);sync();
 db.addEventListener("change",async()=>{if(db.value!=="__new__")return;const n=prompt("Supplier/debtor name"),mbl=prompt("Mobile number");if(!n?.trim()||!mbl?.trim()){db.value="";return}try{await createDebtor(n.trim(),mbl.trim());render();notify("Debtor registered. Select it for the purchase.","success")}catch(err){db.value="";notify(err instanceof Error?err.message:String(err),"error")}});
 f.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(f),p=products.find(x=>x.id===String(fd.get("product"))),q=Number(fd.get("qty")),pr=Number(fd.get("price")),pay=String(fd.get("payment")),prestock=fd.get("prestock")==="on"||pay==="pre_stock",debtor=String(fd.get("debtor")||"")||null;if(!p||q<=0||pr<0)return notify("Invalid purchase details.","error");if(pay==="credit"&&!debtor)return notify("Select a debtor for credit purchase.","error");const base=q,total=p.unit_type==="weight"?base*pr/1000:base*pr,cash=pay==="cash"?total:pay==="split"?total/2:0,upi=pay==="upi"?total:pay==="split"?total/2:0,credit=pay==="credit"?total:0;if(demo){p.current_stock_base+=base;p.purchase_price_per_base_unit=pr;if(!prestock)purchases.unshift({id:"q"+Date.now(),product_id:p.id,product_name_snapshot:p.name,quantity_base:base,quantity_display:q,purchase_unit:p.unit_type==="weight"?"grams":"piece",total_cost:total,purchase_price_per_base_unit:pr,purchased_at:new Date().toISOString(),purchased_by:profile!.id,payment_mode:pay,cash_amount:cash,upi_amount:upi,credit_amount:credit,pre_stock:false});notify(prestock?"Pre-stock recorded.":"Purchase recorded.","success");render();return}const r=await supabase!.rpc("add_inventory_purchase",{p_product_id:p.id,p_quantity_base:base,p_quantity_display:q,p_purchase_unit:p.unit_type==="weight"?"grams":"piece",p_purchase_price:pr,p_payment_mode:pay,p_cash_amount:cash,p_upi_amount:upi,p_credit_amount:credit,p_debtor_id:debtor,p_pre_stock:prestock,p_supplier_name:String(fd.get("supplier")||"")});if(r.error)return notify(r.error.message,"error");await loadData();render()});
}function returnsView(){
 const owner=profile?.role==="owner";if(!owner)return '<section class="page"><div class="panel"><h2>Returns</h2><div class="notice danger">Returns are owner-only.</div></div></section>';
 return '<section class="page"><div class="page-head"><div><h2>Returns</h2><p class="muted">Purchase returns send stock back to suppliers. Sale returns add stock back and reverse the financial effect.</p></div></div><div class="quick-grid"><button id="purchaseReturnBtn" class="primary">↩ Purchase Return</button><button id="saleReturnBtn" class="ghost">↪ Sale Return</button></div><div id="returnForm"></div><div class="panel"><h3>Recent Returns</h3><div class="table-wrap"><table><thead><tr><th>Type</th><th>Product</th><th>Qty</th><th>Amount</th><th>Payment</th><th>Date</th></tr></thead><tbody>'+returnsRows.slice(0,50).map(r=>'<tr><td>'+esc(r.return_type)+'</td><td>'+esc(r.products?.name||r.product_name_snapshot||"Deleted product")+'</td><td>'+esc(r.quantity_display)+' '+esc(r.return_unit)+'</td><td>'+money(r.total_amount)+'</td><td>'+esc(r.payment_mode)+'</td><td>'+fmt(r.returned_at)+'</td></tr>').join("")+'</tbody></table></div></div></section>';
}
function bindReturns(){document.querySelector("#purchaseReturnBtn")?.addEventListener("click",()=>returnForm("purchase"));document.querySelector("#saleReturnBtn")?.addEventListener("click",()=>returnForm("sale"))}
function returnForm(type:"purchase"|"sale"){
 const sale=type==="sale",h=document.querySelector("#returnForm")!;h.innerHTML='<div class="panel"><h3>'+(sale?"Sale Return":"Purchase Return")+'</h3><form id="returnFormInner" class="form-grid"><label>Product<select name="product">'+products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join("")+'</select></label><label>Quantity<input name="qty" type="number" min=".001" step=".001" required></label><label>Unit<select name="unit"><option value="piece">pieces</option><option value="grams">grams</option><option value="kg">kg</option></select></label><label>Return price<input name="price" type="number" min="0" step=".01" required></label><label>Refund / balance<select name="mode"><option value="cash">Cash</option><option value="upi">UPI</option><option value="credit_adjustment">Credit / balance adjustment</option></select></label><label>Original '+(sale?"sale":"purchase")+' ID (optional)<input name="source" placeholder="Paste original ID if available"></label><label class="full">Reason<input name="reason" required placeholder="Reason for return"></label><div id="returnPreview" class="full notice">Enter quantity and price.</div><button class="primary full">Confirm Return</button></form></div>';
 const f=document.querySelector<HTMLFormElement>("#returnFormInner")!,preview=document.querySelector("#returnPreview") as HTMLElement,calc=()=>{const fd=new FormData(f),p=products.find(x=>x.id===String(fd.get("product"))),qty=Number(fd.get("qty")||0),price=Number(fd.get("price")||0),unit=String(fd.get("unit")),base=p?.unit_type==="weight"?(unit==="kg"?qty*1000:qty):qty,total=p?.unit_type==="weight"?base*price/1000:base*price;if(p)preview.textContent="Return amount: "+money(total)+" • Stock will "+(sale?"increase":"decrease")+" by "+base+(p.unit_type==="weight"?" g":" pcs")};f.addEventListener("input",calc);f.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(f),p=products.find(x=>x.id===String(fd.get("product"))),qty=Number(fd.get("qty")),price=Number(fd.get("price")),unit=String(fd.get("unit")),mode=String(fd.get("mode")),source=String(fd.get("source")||"").trim()||null,reason=String(fd.get("reason")||"").trim();if(!p||qty<=0||price<0||!reason)return notify("Enter valid return details.","error");if(p.unit_type==="piece"&&(unit!=="piece"||qty%1!==0))return notify("Piece quantity must be a whole number.","error");if(p.unit_type==="weight"&&!["grams","kg"].includes(unit))return notify("Choose grams or kg.","error");const base=p.unit_type==="weight"?(unit==="kg"?qty*1000:qty):qty;if(!demo){const rpc=sale?"record_sale_return":"record_purchase_return",r=await supabase!.rpc(rpc,{p_product_id:p.id,p_quantity_base:base,p_quantity_display:qty,p_return_unit:unit,p_return_price_per_base_unit:price,p_payment_mode:mode,p_source_id:source,p_reason:reason,p_account_id:null});if(r.error)return notify(r.error.message,"error");await loadData()}else{if(!sale&&p.current_stock_base<base)return notify("Insufficient stock for purchase return.","error");p.current_stock_base+=sale?base:-base;returnsRows.unshift({id:"demo-"+Date.now(),return_type:type,product_id:p.id,product_name_snapshot:p.name,quantity_base:base,quantity_display:qty,return_unit:unit,total_amount:p.unit_type==="weight"?base*price/1000:base*price,payment_mode:mode,returned_at:new Date().toISOString(),products:{name:p.name}})}render()});calc();
}

